on:
  push:
    branches:
      - main
name: Build
jobs:
  build:
    name: Pages
    runs-on: ubuntu-latest
    steps:
    - uses: FranzDiebold/github-env-vars-action@v2
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3
      with:
        node-version-file: 'package.json'
    - run: yarn install
    - run: yarn build
      env:
        REACT_APP_GIT_SHA: ${{ env.CI_SHA_SHORT }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: build
