on:
  push:
    branches:
      - main
name: Build
jobs:
  build:
    name: Pages
    runs-on: ubuntu-latest
    steps:
    - uses: FranzDiebold/github-env-vars-action@v2
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: yarn install
    - run: yarn build
      env:
        REACT_APP_GIT_SHA: ${{ env.CI_SHA_SHORT }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
