on: [push]
name: CI
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.1.0
      env:
        CI: true
      with:
        cmd: test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: lint
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.1.0
      with:
        cmd: build

