on: [push, pull_request]
name: CI
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v3.0.0
      env:
        CI: true
      with:
        cmd: test
    - uses: borales/actions-yarn@v3.0.0
      env:
        CI: true
      with:
        cmd: build
